### ISSUE TITLE
ActiveAdmin DSL

### ISSUE THREAD

**Issue by cappert** [lyonrb/wishlist#44]

**Comment by ranska** [comment]
que propose tu en détail ?
J'aime beaucoup le sujet c'est une gem que j'utilise beaucoup,
je serai ravie d'échanger sur le sujet

**Comment by cappert** [comment]
l'idée c'est qu'il faut utiliser le DSL pour bien se l'approprier donc si on arrive a faire un exemple à la fois simple et bien complet ça pourrait être plus intéressant qu'une énième presentation qui dit que c'est trop cool.

ps c'est suite à une discussion avec @marcpmichel qui bosse aussi avec.

**Comment by marcpmichel** [comment]
J'imagine qu'il faudrait un exemple avec 3 ou 4 modèles, avec ressources nichées (nested resources), affichage custom d'une ressource et d'un formulaire. Un drivy-like ? ( Voitures, Propriétaires, Locataires, Locations )

**Comment by cappert** [comment]
@marcpmichel : comme tu m'as dit que tu avais pas mal de boulot on prévoit pour au moins février ?
@ranska : ravi d'échanger avec toi si tu veux bien passer nous voir :)

**Comment by cappert** [comment]
done feb 2016
